### PR TITLE
Implement Hostnames retrieval

### PR DESCRIPTION
**Pull request by Jupiter79**
I added the hostname feature

It is pretty slow yet but I found no other way to do it.

Maybe change the hostname when it is found and work with multiple threads?

### CODE REVIEW

**Comment by Jupiter79** [comment]
image

**Comment by Jupiter79** [comment]
Untitled

**Comment by elmoiv** [comment]
Thanks for your contribution.

Because socket is called for every device in a serial manner, this will take a noticable long time for the user.

I will update merge your commit for now and update it later.

The modification will be transferring this feature to be threaded in a different QThread and once hostnames are fetched, each cell will be updated automatically, leaving both scan types untouched.

**Comment by steveid53** [comment]
Thank you for all your wonderful effort and work on this project...8-)

**Comment by elmoiv** [comment]
@steveid53 
You're welcome

**Pull request merged**
